
"use client";

import React, { useState, useEffect } from "react";
import { NEW_AI_JOBS } from "../new-ai-jobs/page";

// Record a visit to the chatbot page
async function recordChatbotVisit() {
  try {
    await fetch("/api/visit", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        userAgent: typeof navigator !== 'undefined' ? navigator.userAgent : '',
        path: typeof window !== 'undefined' ? window.location.pathname : '/chatbot-demo'
      })
    });
  } catch (e) {
    // Optionally log error
  }
}

// Simple FAQ and AI job/event recommender chatbot
// Latest announcement/news (update this string as needed)
const ANNOUNCEMENT = "🎉 Happy New Year 2026! Check out our upcoming AI Hiring Events and new job listings for the year ahead. Stay tuned for more updates!";
const FAQS = [
                  {
                    q: "How does this website handle privacy and user data?",
                    a: "Your privacy is important! This website does not collect personal data from visitors unless you choose to contact us or submit information. We comply with privacy laws such as GDPR and CCPA where applicable. For more details, see our Privacy Policy page or contact us with any questions."
                  },
                {
                  q: "How can I get in touch with the site owner?",
                  a: "You can reach out on X (formerly Twitter) at @shellzonit. Feel free to send a message or mention for questions, feedback, or collaboration!"
                },
              {
                q: "Have any books been written by AI?",
                a: "Yes, several books have been written by AI! For example, '1 the Road' (2018) is a novel generated by an AI trained on Jack Kerouac’s 'On the Road.' AI has also been used to co-author poetry, short stories, and non-fiction. These projects show how AI can assist or inspire human writers, opening new creative possibilities."
              },
            {
              q: "What are some ethical concerns with AI?",
              a: "AI raises important ethical questions, such as bias in algorithms, privacy, job displacement, and decision transparency. It's important for developers and users to consider fairness, accountability, and the societal impact of AI systems. Many organizations are working on guidelines and best practices to ensure responsible AI use."
            },
            {
              q: "How does AI impact jobs and society?",
              a: "AI is transforming many industries, automating repetitive tasks, and creating new job opportunities. While some jobs may be replaced, many new roles are emerging in AI development, data analysis, and creative fields. Society benefits from AI in healthcare, education, and accessibility, but it's important to address challenges like inequality and retraining."
            },
            {
              q: "How can I start learning about AI?",
              a: "If you're a beginner, start with online courses like Coursera's 'AI for Everyone' or free resources from Google and Microsoft. Intermediate learners can explore Python programming, machine learning basics, and hands-on projects. Advanced users might dive into deep learning, research papers, or contribute to open source AI projects. Our Resources page has more suggestions!"
            },
            {
              q: "Does using AI make you less intelligent?",
              a: "No, using AI does not make you less intelligent! AI is a tool that can help you be more productive, creative, and informed. Just like calculators or computers, AI assists with complex tasks and frees you to focus on higher-level thinking. The key is to use AI thoughtfully and continue learning alongside it."
            },
          {
            q: "Who are the largest companies hiring for AI jobs?",
            a: "Some of the largest companies hiring for AI roles include Google, Microsoft, Amazon, Meta (Facebook), Apple, NVIDIA, and OpenAI. Many other tech giants, startups, and companies in healthcare, finance, and automotive are also investing heavily in AI talent. These organizations seek AI engineers, data scientists, researchers, and creative technologists to drive innovation."
          },
          {
            q: "Why are plumbers and other blue-collar jobs important for AI and data centers?",
            a: "AI relies on massive data centers that require constant maintenance. Plumbers, electricians, HVAC technicians, and other skilled trades are essential for keeping these facilities running. They install and repair cooling systems, manage water and power infrastructure, and ensure the physical environment is safe for servers. As AI grows, so does the demand for blue-collar workers to support the technology behind the scenes."
          },
        {
          q: "How has AI already been used in games?",
          a: "AI has played a major role in games for decades. Classic examples include the ghosts in Pac-Man (1980), which use simple AI to chase the player, and the adaptive enemies in the 'Halo' series. Modern games use AI for NPC behavior, procedural world generation (like in 'Minecraft'), and even for testing and balancing gameplay. AI helps create more immersive, challenging, and dynamic experiences."
        },
        {
          q: "How has AI already been used in movies?",
          a: "AI is widely used in movies for visual effects, animation, and even scriptwriting. For example, AI-powered software helps create realistic CGI characters and environments, as seen in movies like 'Avengers: Endgame' and 'The Lion King' (2019). AI is also used for deepfake technology, voice synthesis, and editing. Some filmmakers experiment with AI-generated scripts and storyboards, pushing the boundaries of creativity in cinema."
        },
      {
        q: "What was the first AI-generated song?",
        a: "The first known AI-generated song was created in 1956 by researchers at Bell Labs using an IBM 704 computer. The program, written by Lejaren Hiller and Leonard Isaacson, generated a piece called the 'Illiac Suite' for string quartet. This marked the beginning of computer-generated music and showed that AI could be used creatively in music composition, a trend that has grown for decades."
      },
    {
      q: "How is AI used in games?",
      a: "AI is revolutionizing game development by powering smarter NPCs, procedural content generation, adaptive difficulty, and even game testing. AI tools help designers create more immersive and dynamic experiences. Careers include AI Game Designer, Game AI Programmer, and Narrative Designer."
    },
    {
      q: "How is AI used in music?",
      a: "AI is transforming music by enabling generative composition, intelligent mixing, and personalized recommendations. Artists use AI to create new sounds, collaborate with virtual musicians, and analyze trends. Careers include AI Music Producer, Sound Designer, and Music Data Analyst."
    },
  {
    q: "What is this site about?",
    a: "Auralis Sanctuary is a creative sanctuary dedicated to helping you thrive in the age of AI. We offer curated AI job listings, hiring events, resources, and community support for creative and technical talent. Whether you're looking to start a new career, upskill, or connect with others, you'll find guidance and opportunities here."
  },
  {
    q: "How do I find AI jobs?",
    a: "Visit the New AI Jobs page for a curated list of emerging roles, required skills, and employers. You can filter jobs by interest, skill set, or location. We regularly update listings to reflect the latest opportunities in AI, creative tech, and related fields."
  },
  {
    q: "What are AI hiring events?",
    a: "AI hiring events are job fairs, networking sessions, and workshops where you can meet recruiters, learn about open positions, and connect with industry leaders. Many events are hybrid or virtual, making it easy to participate from anywhere. Check the AI Hiring Events page for upcoming dates and details."
  },
  {
    q: "How can I prepare for an AI career?",
    a: "Explore our resources section for recommended courses, training programs, and articles. Attend hiring events to network and learn from experts. Consider building a portfolio of projects, contributing to open source, and staying updated on AI trends. We also share tips on resume building and interview prep."
  },
  {
    q: "Can I get career advice?",
    a: "Absolutely! Ask me about career paths, required skills, or how to transition into AI roles. You can also reach out through our contact page for personalized advice or mentorship opportunities."
  },
  {
    q: "Are there opportunities for beginners?",
    a: "Yes! Many AI jobs and events welcome beginners and those from non-technical backgrounds. Look for roles like AI Content Curator, Prompt Engineer, or Community Manager. Our resources page highlights beginner-friendly learning paths."
  }
];

const JOB_SUGGESTIONS = [
    {
      keyword: "games",
      suggestion: "Explore roles like AI Game Designer, Game AI Programmer, and Narrative Designer. AI is used for smarter NPCs, procedural worlds, and player analytics in the gaming industry."
    },
    {
      keyword: "music",
      suggestion: "Consider careers such as AI Music Producer, Sound Designer, or Music Data Analyst. AI is used for generative music, intelligent mixing, and music recommendation systems."
    },
  {
    keyword: "creative",
    suggestion: "You might enjoy roles like Generative Content Creator, AI Art Director, or AI Trainer. These positions blend creativity with technology and are in high demand. Check the New AI Jobs page for more."
  },
  {
    keyword: "coding",
    suggestion: "Consider roles such as AI Engineer, Machine Learning Engineer, or Data Scientist. These jobs require programming skills and offer opportunities to work on cutting-edge projects. See the New AI Jobs page for details."
  },
  {
    keyword: "education",
    suggestion: "AI Curriculum Designer, Prompt Engineer, and AI Literacy Advocate are great options for those passionate about teaching and learning."
  },
  {
    keyword: "remote",
    suggestion: "Many AI jobs and events are remote-friendly. Look for Remote AI Talent Fair and virtual networking sessions on the events page."
  },
  {
    keyword: "manager",
    suggestion: "AI Project Manager and Community Manager roles are perfect for those with leadership and organizational skills."
  },
  {
    keyword: "art",
    suggestion: "Explore opportunities as an AI Art Curator, Digital Artist, or Creative Technologist. The intersection of art and AI is growing rapidly."
  },
  {
    keyword: "writing",
    suggestion: "AI Content Writer, Technical Writer, and Prompt Engineer are excellent roles for strong communicators."
  },
  {
    keyword: "events",
    suggestion: "Check out upcoming AI Career Expos, Women in AI Summits, and virtual talent fairs. These events offer networking, workshops, and direct access to recruiters."
  },
  {
    keyword: "beginner",
    suggestion: "If you're just starting out, look for internships, junior roles, or volunteer opportunities in AI projects. Many companies offer mentorship and training for beginners."
  }
];


export default function ChatbotDemo() {
  const [visitorNum, setVisitorNum] = useState<number | null>(null);
  const [messages, setMessages] = useState<{from: string, text: string}[]>([]);
  const [input, setInput] = useState("");
  const [loading, setLoading] = useState(false);

  // On mount, increment and get visitor number from localStorage
  useEffect(() => {
    let num = 1;
    try {
      const stored = localStorage.getItem("chatbot-visitor-num");
      if (stored) {
        num = parseInt(stored, 10) + 1;
      }
      localStorage.setItem("chatbot-visitor-num", num.toString());
    } catch {}
    setVisitorNum(num);
    setMessages([
      { from: "bot", text: `Welcome! You are visitor number ${num} on this browser. Ask me anything about this site, AI jobs, or events.` }
    ]);
    recordChatbotVisit();
  }, []);

    function getBotResponse(userMsg: string) {
      const msg = userMsg.toLowerCase();
      // 1. Announcement/news match
      if (/(news|announcement|update|what's new|latest)/.test(msg)) {
        return ANNOUNCEMENT;
      }
      // Who is the site owner/creator/admin
      if ((msg.includes("who runs") || msg.includes("who is behind") || msg.includes("who created") || msg.includes("who made") || msg.includes("site owner") || msg.includes("admin") || msg.includes("creator") || msg.includes("who are you") || msg.includes("who am i") || msg.includes("who is the owner") || msg.includes("who is the admin") || msg.includes("who is the creator") || msg.includes("who is shellzonit") || msg.includes("what are you")) && (msg.includes("site") || msg.includes("website") || msg.includes("chatbot") || msg.includes("sanctuary") || msg.includes("auralis") || msg.includes("shellzonit") || msg.includes("you") || msg.includes("admin") || msg.includes("owner") || msg.includes("creator"))) {
        return "This website and chatbot were created and are managed by Shellzonit (also known as @shellzonit on X/Twitter). Shellzonit is a creative technologist and community builder focused on helping people thrive in the age of AI. You can reach out for questions, feedback, or collaboration via X (formerly Twitter) at @shellzonit.";
      }

      // How can a person help train the chatbot/AI and can it lead to a career
      if ((msg.includes("train you") || msg.includes("train the ai") || msg.includes("train chatbot") || msg.includes("help train") || msg.includes("how can i train") || msg.includes("can i train") || msg.includes("be used to train") || msg.includes("data labeling") || msg.includes("ai trainer") || msg.includes("become an ai trainer") || msg.includes("can i work as ai trainer") || msg.includes("can i get a job training ai"))) {
        return "People play a crucial role in training AI and chatbots! You can help by labeling data, providing feedback on AI outputs, or participating in user studies. This process is called 'data annotation' or 'AI training.' Many companies hire 'AI Trainers' or 'Data Annotators' to improve AI systems. These roles often require attention to detail and basic computer skills, and can be a great entry point into an AI career. Over time, you can advance to more specialized roles in AI development, quality assurance, or data science. Check out the 'AI Trainer' job in the New AI Jobs section for more info and resources on how to get started.";
      }
      // Easiest AI career question
      if ((msg.includes("easiest") || msg.includes("easy") || msg.includes("least training") || msg.includes("minimal training") || msg.includes("no experience") || msg.includes("beginner")) && (msg.includes("ai career") || msg.includes("ai job") || msg.includes("ai field") || msg.includes("ai work"))) {
        // Find the job with the lowest barrier to entry (based on pay and required skills)
        const entryJobs = NEW_AI_JOBS.filter(job => job.pay && (job.pay.includes("40,000") || job.pay.includes("60,000") || job.title.toLowerCase().includes("trainer") || job.title.toLowerCase().includes("content creator")));
        if (entryJobs.length > 0) {
          const easiest = entryJobs[0];
          return `One of the easiest AI careers to start with minimal training is **${easiest.title}**. ${easiest.description} This role often requires only basic skills such as ${easiest.skills.join(", ")}, and you can get started with resources like: ${easiest.resources.join(", ")}. Typical pay ranges from ${easiest.pay}.`;
        } else {
          return "Many entry-level AI jobs such as AI Trainer or Generative Content Creator require less training and are open to beginners. Look for roles that focus on data labeling, content creation, or supporting AI teams. Check the New AI Jobs page for more details.";
        }
      }
      // 2. List all AI jobs if user asks for a list
      if (
        (msg.includes("ai jobs") || msg.includes("list ai jobs") || msg.includes("all ai jobs") || msg.includes("what are the ai jobs") || msg.includes("show ai jobs") || msg.includes("available ai jobs") || msg.includes("types of ai jobs") || msg.includes("what do ai jobs do") || msg.includes("what is an ai job") || msg.includes("what are ai careers") || msg.includes("explain ai jobs") || msg.includes("tell me about ai jobs"))
      ) {
        return `AI jobs are roles that involve working with artificial intelligence technologies, such as building, training, or applying AI models and systems. Here are some AI jobs you can explore:\n\n${NEW_AI_JOBS.map(job => `• ${job.title}`).join("\n")}\n\nYou can ask about any job above to learn more about its responsibilities, required skills, and pay.`;
      }
      // 3. AI job definitions, qualifications, and pay
      for (const job of NEW_AI_JOBS) {
        const jobName = job.title.toLowerCase();
        // Certification or training questions
        if (
          (msg.includes("certification") || msg.includes("certificate") || msg.includes("certify") || msg.includes("training") || msg.includes("course") || msg.includes("learn") || msg.includes("where can i get certified") || msg.includes("how do i get certified")) &&
          msg.includes(jobName)
        ) {
          return `To get certified or trained for the role of **${job.title}**, you can explore these recommended resources: ${job.resources.join(", " )}. These programs and courses are a great way to build the skills needed for this job. Check their official websites for details on certification requirements and enrollment.`;
        }
        // General job info
        if (
          msg.includes(jobName) ||
          (msg.includes("define") && msg.includes(jobName)) ||
          (msg.includes("qualification") && msg.includes(jobName)) ||
          (msg.includes("pay") && msg.includes(jobName)) ||
          (msg.includes("salary") && msg.includes(jobName))
        ) {
          return `**${job.title}**\n\n${job.description}\n\n**Required Skills:** ${job.skills.join(", ")}\n**Industries:** ${job.industries.join(", ")}\n**Example Employers:** ${job.employers.join(", ")}\n**Training Resources:** ${job.resources.join(", ")}\n**Typical Pay Range:** ${job.pay}`;
        }
      }
      // 4. General site/about questions
      if (
        msg.includes("about this site") ||
        msg.includes("what is this site") ||
        msg.includes("what does this site do") ||
        msg.includes("what is sanctuary") ||
        msg.includes("what is auralis sanctuary") ||
        msg.includes("what does this website do") ||
        msg.includes("tell me about this site") ||
        msg.includes("site purpose") ||
        msg.includes("site info") ||
        msg.includes("website info") ||
        msg.includes("what is this for")
      ) {
        return "Auralis Sanctuary is a creative sanctuary dedicated to helping you thrive in the age of AI. We offer curated AI job listings, hiring events, resources, and community support for creative and technical talent. Whether you're looking to start a new career, upskill, or connect with others, you'll find guidance and opportunities here.";
      }
      // 5. FAQ match
      const faq = FAQS.find(f => msg.includes(f.q.toLowerCase().split(" ")[0]));
      if (faq) return faq.a;
      // 4. Job suggestion
      const jobSuggestion = JOB_SUGGESTIONS.find(j => msg.includes(j.keyword));
      if (jobSuggestion) return jobSuggestion.suggestion;
      // 5. Fallback
      return "I'm here to help with questions about AI jobs, events, and resources! Try asking about careers, events, or training. For the latest news, ask 'What's new?'";
    }

  const handleSend = (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    if (!input.trim()) return;
    const userMsg = input.trim();
    setMessages(msgs => [...msgs, { from: "user", text: userMsg }]);
    setInput("");
    setLoading(true);
    setTimeout(() => {
      const botReply = getBotResponse(userMsg);
      setMessages(msgs => [...msgs, { from: "bot", text: botReply }]);
      setLoading(false);
    }, 600);
  };

  return (
    <main style={{ minHeight: "100vh", background: "linear-gradient(135deg, #0a141a 0%, #18191a 60%, #2a1a4d 100%)", fontFamily: "Inter, Arial, sans-serif", display: "flex", flexDirection: "column", alignItems: "center", padding: "0 1rem" }}>
      <h1 style={{ fontSize: "2rem", fontWeight: 800, color: "#ffd700", margin: "32px 0 16px 0", textShadow: "0 2px 16px #6a1b9a" }}>
        Chatbot Demo: AI Jobs & FAQ
      </h1>
      {/* Announcement/news banner */}
      <div style={{
        background: "#ffd700",
        color: "#232526",
        borderRadius: 10,
        padding: "10px 18px",
        fontWeight: 700,
        marginBottom: 18,
        boxShadow: "0 2px 12px #6a1b9a22",
        maxWidth: 520,
        width: "100%",
        textAlign: "center",
        letterSpacing: 0.1,
      }}>
        {ANNOUNCEMENT}
      </div>
      <section style={{ maxWidth: 500, width: '100%', background: "rgba(255,255,255,0.07)", borderRadius: 16, padding: 24, boxShadow: "0 2px 16px #6a1b9a22", marginBottom: 32 }}>
        <div style={{ minHeight: 220, marginBottom: 16 }}>
          {messages.map((msg, i) => (
            <div key={i} style={{
              textAlign: msg.from === "bot" ? "left" : "right",
              color: msg.from === "bot" ? "#ffd700" : "#fff8dc",
              margin: '8px 0',
              fontWeight: msg.from === "bot" ? 700 : 400
            }}>{msg.text}</div>
          ))}
          {loading && <div style={{ color: '#ffd700', fontStyle: 'italic' }}>Bot is typing…</div>}
        </div>
        <form onSubmit={handleSend} style={{ display: 'flex', gap: 8 }}>
          <input
            value={input}
            onChange={e => setInput(e.target.value)}
            style={{ flex: 1, borderRadius: 8, border: '1.5px solid #ffd700', padding: '10px 14px', fontSize: '1rem', background: '#18191a', color: '#fff8dc' }}
            placeholder="Type your question..."
            disabled={loading}
            autoFocus
          />
          <button type="submit" style={{ background: '#ffd700', color: '#232526', fontWeight: 700, borderRadius: 8, padding: '10px 18px', border: 'none', cursor: 'pointer' }} disabled={loading || !input.trim()}>
            Send
          </button>
        </form>
      </section>
      <div style={{ color: '#fff8dc', fontSize: '1rem', marginTop: 24, textAlign: 'center', maxWidth: 600 }}>
        <strong>How it works:</strong> This chatbot answers FAQs, shares the latest news, and suggests AI jobs/events based on your interests. Try asking about jobs, events, news, or how to get started!
      </div>
    </main>
  );
}
